### ISSUE TITLE
Bot closing all issues indiscriminately

### ISSUE THREAD

**Issue by robphoenix** [kytrinyx/golang-tour-boilerplate-responder#1]
The bot appears to be automatically closing all issues:

https://github.com/golang/tour/issues/240
https://github.com/golang/tour/issues/238
https://github.com/golang/tour/issues/239
https://github.com/golang/tour/issues/237

**Comment by kytrinyx** [comment]
Shoot. Thanks for catching this, so sorry! You should be able to reopen those issues now.

**Comment by robphoenix** [comment]
No worries, I had a look at the code here, but I don't understand enough to see why this is happening, sorry I can't open a PR to help with this.

**Comment by kytrinyx** [comment]
This is the first ever javascript I've ever written. I'm now figuring out how to write tests :)

**Comment by kytrinyx** [comment]
Aaaaand it's a regex thing where I was matching on a group because I forgot to escape the square brackets. I have tests this time.

**Comment by kytrinyx** [comment]
@robphoenix I've deployed the fix and turned the bot back on.

**Comment by robphoenix** [comment]
Great, glad to hear you found the problem! :tada: Of course it was a regex thing! :laughing: 
Yay for tests.
